import { supabase } from './supabase';
import type { Product } from '@/types';

// ─── Fetch active products from Supabase ───
// Images are stored as a direct URL field on the product (Firebase Storage)
export async function fetchProducts(): Promise<Product[]> {
  const { data, error } = await supabase
    .from('products')
    .select('id, name, price, category, description, popular, image_url')
    .eq('status', 'active')
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching products:', error);
    return [];
  }

  return (data || []).map((p) => ({
    id: p.id,
    name: p.name,
    price: p.price,
    category: p.category as Product['category'],
    description: p.description || '',
    popular: p.popular || false,
    image: p.image_url || '/products/case-amirah.png',
  }));
}

// ─── Fetch shipping rates from Supabase ───
export async function fetchShippingRates() {
  const { data, error } = await supabase
    .from('shipping_rates')
    .select('*')
    .order('wilaya_code');

  if (error) {
    console.error('Error fetching shipping rates:', error);
    return [];
  }

  return data || [];
}

// ─── Submit order ───
export interface OrderSubmission {
  customerName: string;
  customerPhone: string;
  wilaya: string;
  address: string;
  notes: string;
  items: {
    productId: string;
    phoneModelName: string; // hardcoded model name, not DB id
    quantity: number;
    unitPrice: number;
    isCustom?: boolean;
    customDescription?: string;
    designImages?: string[]; // Firebase Storage URLs
  }[];
  totalAmount: number;
  shippingCost: number;
}

export async function submitOrder(order: OrderSubmission) {
  // 1. Create the order
  const { data: orderData, error: orderError } = await supabase
    .from('orders')
    .insert({
      order_number: '', // auto-generated by trigger
      customer_name: order.customerName,
      customer_phone: order.customerPhone,
      wilaya: order.wilaya,
      address: order.address,
      notes: order.notes,
      total_amount: order.totalAmount,
      shipping_cost: order.shippingCost,
      status: 'pending',
    })
    .select('id, order_number')
    .single();

  if (orderError || !orderData) {
    console.error('Error creating order:', orderError);
    throw new Error('Failed to create order');
  }

  // 2. Create order items
  const orderItems = order.items.map(item => ({
    order_id: orderData.id,
    product_id: item.isCustom ? null : item.productId,
    phone_model: item.phoneModelName, // store model name directly
    quantity: item.quantity,
    unit_price: item.unitPrice,
    is_custom: item.isCustom || false,
    custom_description: item.customDescription || '',
  }));

  const { data: itemsData, error: itemsError } = await supabase
    .from('order_items')
    .insert(orderItems)
    .select('id');

  if (itemsError) {
    console.error('Error creating order items:', itemsError);
    throw new Error('Failed to create order items');
  }

  // 3. Attach custom design images (Firebase URLs) if any
  const imageInserts: { order_item_id: string; image_url: string; sort_order: number }[] = [];
  order.items.forEach((item, idx) => {
    if (item.designImages?.length && itemsData?.[idx]) {
      item.designImages.forEach((url, imgIdx) => {
        imageInserts.push({
          order_item_id: itemsData[idx].id,
          image_url: url,
          sort_order: imgIdx,
        });
      });
    }
  });

  if (imageInserts.length > 0) {
    await supabase.from('order_item_images').insert(imageInserts);
  }

  return {
    orderId: orderData.id,
    orderNumber: orderData.order_number,
  };
}

// ─── Store settings (read-only from storefront) ───
export async function getStoreSetting(key: string): Promise<string> {
  const { data, error } = await supabase
    .from('store_settings' as any)
    .select('value')
    .eq('key', key)
    .single();
  if (error) return '';
  return (data as any)?.value || '';
}
